In [1]:
import torch 
import torch.nn as nn

In [2]:
# Inputs 

inputs = torch.tensor([1.0, 2.0, 3.0])

In [3]:
neuron = nn.Linear(in_features = 3, out_features = 1)

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([-0.8524], grad_fn=<ViewBackward0>)

In [6]:
# verify formuls 

neuron.weight @ inputs + neuron.bias

tensor([-0.8524], grad_fn=<AddBackward0>)

In [7]:
# neuron.weight
neuron.bias

Parameter containing:
tensor([-0.5182], requires_grad=True)