In [4]:
import torch 
import torch.nn as nn

In [39]:
# Inputs 

inputs = torch.tensor([1.0, 2.0, 3.0])

In [41]:
neuron = nn.Linear(in_features = 3, out_features = 1)

In [43]:
output = neuron(inputs)

In [45]:
output

tensor([0.3649], grad_fn=<ViewBackward0>)

In [47]:
# verify formuls 

neuron.weight @ inputs + neuron.bias

tensor([0.3649], grad_fn=<AddBackward0>)

In [49]:
# neuron.weight
neuron.bias

Parameter containing:
tensor([0.3053], requires_grad=True)